### ISSUE TITLE
Password reset

### ISSUE THREAD

**Issue by shota-mentesh** [mageplaza/magento-2-social-login#134]
### Preconditions

1. Magento: 2.2.6
2. PHP: 7.0.33
3. MySQL: 5.7.25

### Steps to reproduce

1. Go to password reset popup
2. Fill in all the required fields
3. Click submit

### Expected result

1. HTTP status code should be 200 not 500.

### Actual result

1. Response HTTP status code is 500 and popup loading never ends. Although response clearly says that everything is OK. Mail is successfully sent as well.
![image](https://user-images.githubusercontent.com/39200660/53813187-7c8fcb00-3f76-11e9-8e44-03db9cc9e26b.png)

**Comment by bien119** [comment]
Hi @shota-mentesh 
I was checking your issue and saw that HTTP status returns 200.
See the Screenshot: http://prntscr.com/muhmd4
"The popup will be loading never ends" Could you show me more about that?

**Comment by bien119** [comment]
@shota-mentesh This issue has been closed because there has been no response to our request for more information from you. With only the information that is currently in the issue, we don't have enough information to take action. Please reach out if you have or find the answers we need so that we can investigate further.
