### ISSUE TITLE
Facebook icon doesn't show

### ISSUE THREAD

**Issue by mrk-dzie** [mageplaza/magento-2-social-login#149]
After enabling login from Facebook and Google the icon of Facebook doesn't show. I am using Font Awesome and it seems that brands icons need to have prefix class "fab", but it has "fa" prefix class.
Google icon is visible cuz overriding style for class ".btn-google .fa-google" set background image

**Comment by Victor-Mageplaza** [comment]
Hi @mrk-dzie 
I'm Victor from Mageplaza.
Can you tell me where the button is not displayed?
Ex: Social pop-up, customer-login-page, etc ...

**Comment by mrk-dzie** [comment]
Customer login/creating account page
![social-login-buttons](https://user-images.githubusercontent.com/8580499/63694658-375aa080-c817-11e9-866f-5bdcff795610.png)

**Comment by Victor-Mageplaza** [comment]
Hi @mrk-dzie 
Can you check your Font Awesome version?
Our module uses Font Awesome 4.6.3 but because our module is always running at low flow, it is possible that the site has used Font Awesome with your version.
That leads to conflict and it causes your problem.
You can contact us through the support department so we can help you solve this problem.

**Comment by Victor-Mageplaza** [comment]
Hi @mrk-dzie 
Since you were unable to respond within the time range, I will close this issue.
If the problem still persists, you can contact us via the support portal.
Thank you.
