### ISSUE TITLE
Social Login Compatibility with Hybridauth v 3.0.0

### ISSUE THREAD

**Issue by piotrusin** [mageplaza/magento-2-social-login#161]
https://github.com/mageplaza/magento-2-social-login/issues/70#issuecomment-548667233

**Comment by Victor-Mageplaza** [comment]
Hi @piotrusin 
I'm Victor from Mageplaza. I would like to answer your question.
We are currently using hybrid auth v2.0. However, in order to upgrade using v3.0, the module structure needs to change and this takes time.
It is certain that in the next versions, the use of v3.0 will become clearer.
Hope you always support our module. Thank you!
