### ISSUE TITLE
Composer installation required many unrelated Mageplaza´s extensions. Why ?

### ISSUE THREAD

**Issue by gustavoulyssea** [mageplaza/magento-2-social-login#166]
I got this via composer and it installed many unrelated Mageplaza´s extensions. Why ? Please fix it. This extension stuffing caused bugs.
 
### Preconditions

1. Magento: 2.3.2
2. PHP: 7.1
3. MySQL: -
4. 

### Steps to reproduce

1. composer require mageplaza/magento-2-social-login
2. 
3. 

### Expected result

1. Install Social Login, maybe Core if needed.

### Actual result

1. [Screenshot, logs]
Installed many things such as email (???)

**Comment by Victor-Mageplaza** [comment]
I'm Victor from Mageplaza. I would like to answer your question.

The many extensions that come with SocialLogin when installed via the composer are because those extensions support a certain function of SocialLogin.
It is true that sometimes this is a nuisance when it installs too many modules that customers do not have time to manage.
In my opinion, the temporary solution is to install it manually on the app/code section to avoid this situation.

Thank you!
