### ISSUE TITLE
Magento Popuplogin Issue, even when Logged in By  Social Media Account 

### ISSUE THREAD

**Issue by Hades1295** [mageplaza/magento-2-social-login#197]
Gives Social login Popup even after logging in, on Proceed to checkout.
### Preconditions

1. Magento: 2.3.4
2. PHP: 7.2

### Steps to reproduce

1.  In Incognito Browser,
2. Click on Login via Google/Facebook.
3.  Add to cart and Proceed to checkout.

### Expected result

1.It should Let me Proceed to checkout.

### Actual result

1. [Screenshot, logs]

**Already Logged in**
![Screenshot from 2020-07-29 15-58-10](https://user-images.githubusercontent.com/43248419/88789964-0ae09e80-d1b5-11ea-92b2-40024cf254d4.png)

**Adding to cart** 
![Screenshot from 2020-07-29 15-58-25](https://user-images.githubusercontent.com/43248419/88790009-1b911480-d1b5-11ea-9493-f8e9dd2199c7.png)

**On Proceeding to checkout** 
![Screenshot from 2020-07-29 15-58-40](https://user-images.githubusercontent.com/43248419/88790039-2c418a80-d1b5-11ea-9506-fc50b3433af4.png)

**Comment by Victor-Mageplaza** [comment]
Hi @Hades1295 
I have encountered many similar cases. Probably because of the loading order in M ​​2.3.4 and M 2.3.5 versions are having problems. There is a simple way to use **customerData.reload(true);** in any JS file but it doesn't seem to be very optimized.
I am looking for a more optimal way for this problem. Thanks!
Simple way you should add **customerData.reload(true);** to JS file

**Comment by Hades1295** [comment]
@Victor-Mageplaza  in which js file do we need to add the **customerData.reload(true);**.

**Comment by Victor-Mageplaza** [comment]
@Hades1295 
For example: if you use the popup option of social login, you can add like this: http://prntscr.com/tr04ol
On _**<your_magento_root>\SocialLogin\view\frontend\web\js\popup.js**_
Or you can create a new JS file and put this code into
Thank you!
