### ISSUE TITLE
Login & Create Account Idle After Successfull Sign in at Facebook / Google

### ISSUE THREAD

**Issue by wilhelmaitan** [mageplaza/magento-2-social-login#202]
### Preconditions

1. Magento: 2.3.5p1
2. PHP: PHP 7.2.29 
3. MySQL: Server version: 5.6.40-84.0-log - Percona Server (GPL), Release 84.0, Revision 47234b3 
4. Social Login Version: v2.8.3

### Steps to reproduce

1. Facebook App and Google Project Successfully Configured as per documentation

### Expected result

1.  Sign in / Create Account successful

### Actual result

1. Customer goes to Login or create account page
2. Customer clicks on sign in with facebook / google
3. Facebook / Google Popup Opens and Ask user to sign in to their social account
4. After Successful sign in "In Popup" / The Popup closes and nothing happens.
5. Customer again clicks on sign in with facebook / sign in with google - Pop up won't open.
6. No Error shows on front end 

--
No Error in Exception log
Debug Log shows following error:

[2020-09-28 06:46:27] main.DEBUG: URI '/customer/account/loginPost/referer/aHR0cHM6Ly9waW5xLmNvL2Ntcy9ub3JvdXRlL2luZGV4L3VlbmMvYUhSMGNITTZMeTl3YVc1eExtTnZMMlYyWlhKNVpHRjVMV0p2ZUM1b2RHMXMvcHJvZHVjdC8yOS90ZXN0aW1vbmlhbHMvdGVzdGltb25pYWxzL3BpbnEtYm94ZXMvcGVlLW9udGhlLWdvLmh0bWwv/'' cannot be accessed with GET method (Magento\Customer\Controller\Account\LoginPost) [] []
[2020-09-28 06:46:27] main.DEBUG: Request validation failed for action "Magento\Customer\Controller\Account\LoginPost\Interceptor" {"exception":"[object] (Magento\\Framework\\App\\Request\\InvalidRequestException(code: 0): Invalid request received at /public_html/vendor/magento/framework/App/Request/HttpMethodValidator.php:69)"} []

**Comment by Victor-Mageplaza** [comment]
Hi @wilhelmaitan 

I'm Victor from Mageplaza. I would like to answer your issue.

The current problem that you are facing has many causes.
Since I tried to reproduce it on my local site before but with no success.
So I can just list a bunch of possible causes for the problem for you to check again:

- This issue is related to your site's cache and session settings. Chances are the incorrect port setting when using Varnish was the cause of the problem

-/customer/account/loginPost/referer/aHR0cHM6Ly9waW5xLmNvL2Ntcy9ub3JvdXRlL2luZGV4L3VlbmMvYUhSMGNITTZMeTl3YVc1eExtTnZMMlYyWlhKNVpHRjVMV0p2ZUM1b2RHMXMvcHJvZHVjdC8yOS90ZXN0aW1vbmlhbHMvdGVzdGltb25pYWxzL3BpbnEtYm94ZXMvcGVlLW9udGhlLWdvLmh0bWwv/'' cannot be accessed with GET method -- GET method is not accepted by Magento, I will check the code in the module once

- public_html/vendor/magento/framework/App/Request/HttpMethodValidator.php:69 -- Does your site use HTTPS yet? All current providers require users to use HTTPS in order to use their APIs


Those are the closest possibilities to your problem through the data you provided me.
Please check back and let me know.
I would also to find out the exact cause to improve this module's problem. Looking forward to your support.
Have a nice day. Thank you!

Best Regards
Victor

**Comment by wilhelmaitan** [comment]
Hi @Victor-Mageplaza 

1. I'm using Nginx and have Full Page cache disabled.
2. Yes, my site uses HTTPS and everything else is working fine. (Normal Login, Register, Checkout etc.)
3. Let me know if you would need any further details?
4. I have made 2 more changes to the code, though the problem was already there and still persist. 
    - customerData.reload(true); in popup.js
    - $customer = $this->apiObject->getCustomerBySocial($userProfile->identifier, $type); in login.php

Best Regards
Wilhelm

**Comment by Victor-Mageplaza** [comment]
Hi @wilhelmaitan 

Yes, I understand. I will check again on my side.
Then I'll let you know the results.
Many thanks for your information.
Also, if you have any ideas then don't hesitate to try and let me know the results.
It will most likely be the key to solving the problem. Thank you!

Best Regards
Victor

**Comment by nandhu-vn** [comment]
I am using magento v2.4.1. The same issue exists for me also. Is there any fixes available?

**Comment by ismailcaakir** [comment]
I am having the same problem.Is it fixed?

**Comment by Poojathakkarbrainvire** [comment]
Please try setting Require Enter Password to No 
https://i.imgur.com/QliyD8s.png
