### ISSUE TITLE
Can't sign in with Facebook

### ISSUE THREAD

**Issue by vladsmirnov** [mageplaza/magento-2-social-login#206]
Sign in with Facebook doesn't work.

### Preconditions

1. Magento:  2.4.1 Commerce
2. PHP: 7.4
3. MySQL: 10.2

### Steps to reproduce

1. go to customer account create page
2. click on the Facebook button
3. allow getting a facebook user data
4. error is being appeared 

### Expected result

1. customer should sign in

### Actual result

1. user gets an error message in the standard Magento message box
`5.7.9 Please log in with your web browser and then try again. Learn more at 5.7.9 https://support.google.com/mail/?p=WebLoginRequired s8sm2838323pjn.46 - gsmtp`

The same happening on your demo showroom: https://social-login-pro.demo2.mageplaza.com/

**Comment by vladsmirnov** [comment]
I guess it's related to email configurations

**Comment by Victor-Mageplaza** [comment]
Hi @vladsmirnov 

I'm Victor from Mageplaza. I would like to answer your question.

Yes, you are right. Your issue caused by SMTP.
I found an article detailing this issue and how to fix it. Here is the link:
https://stackoverflow.com/questions/20337040/getting-error-while-sending-email-through-gmail-smtp-please-log-in-via-your-w

Please try again and let me know.
Thank you!

Best Regards,
Victor
