### ISSUE TITLE
Social not working after set "Allow guest checkout" config

### ISSUE THREAD

**Issue by HoangTN96** [mageplaza/magento-2-social-login#232]
Hi Team.
I have an isssue after set "Allow guest checkout" config at backend.
after login by fb,google I didn't process to checkout by button "process to checkout" on minicart, it show popup login.
Note: only occur  when the site  load first time, when i logout and login again. all work fine.
Can you help me check it. Thank you!

**Comment by Victor-Mageplaza** [comment]
I'm Victor from Mageplaza. I would like to answer your questions.

I have encountered many similar cases. Probably because of the loading order in M ​​2.3.4 and M 2.3.5 versions are having problems. There is a simple way to use **customerData.reload(true);** in any JS file. Thanks!

Best Regards,
Victor

**Comment by HoangTN96** [comment]
Hi @Victor-Mageplaza 
Thank for your sugestion. 
I tried adding this code when the page load, it is resolved but I am not sure it will not effect to all sessions

require([
           'Magento_Customer/js/customer-data'
        ], function (customerData) {
            var sections = ['cart'];
             var customer= ['customer'];
            customerData.invalidate(sections);
            customerData.reload(sections, true);
            customerData.invalidate(customer);
            customerData.reload(customer, true);
        });
