### ISSUE TITLE
Cannot Close the Popup when I click "x" at the top right

### ISSUE THREAD

**Issue by TenzinNKhando** [mageplaza/magento-2-social-login#52]
Clicking the "x" on the popup does not close the popup. However, clicking outside of the popup and 'Esc' on the keyboard closes the popup. 
### Preconditions

1. Magento: 2.1.5
2. PHP: 7.0.15
3. MySQL: 5.7.17

### Steps to reproduce

1. Open the popup at homepage
2. Click the "x" at the top right of the popup
3. The "x" disappears and adds extra margin to the <button>
4. Click anywhere within the popup and "x" reappears

### Expected result

1. Open the popup
2. Click "x"
3. Popup disappears

### Actual result

1. [Screenshot, logs]
![image](https://user-images.githubusercontent.com/13293090/29133871-b694de68-7ce9-11e7-9d62-ab2c99bfc5cd.png)
![image](https://user-images.githubusercontent.com/13293090/29133904-d09c1f2e-7ce9-11e7-9bd0-157fdc235f1d.png)

**Comment by MaxxLuong** [comment]
Hi TenzinNKhando,
It's working well on my local machine, you can check my video here: [https://www.screencast.com/t/g0paSuhs](https://www.screencast.com/t/g0paSuhs)
The problem which you got is caused by your theme conflict with Social Login.
We need site link to check the problem. Please provide it for us.

Thank you very much.

**Comment by TenzinNKhando** [comment]
Thank you for the response. 

You can see the problem in our development site: https://dev.americanretailsupply.com/

**Comment by TenzinNKhando** [comment]
@MaxxLuong Thank you so much! That fixed the problem
