### ISSUE TITLE
Social Login not shown on checkout page

### ISSUE THREAD

**Issue by afavata** [mageplaza/magento-2-social-login#63]
Hello 

I think it would be useful to have social buttons integrated in the Checkout page.
Also in the checkout page clicking on "Sign In" no social buttons are shown.

Please see Mageplaza Social Loging Demo Site at:
http://sociallogin.demo.mageplaza.com/checkout/

Thank you 

Alex

**Comment by imsamthomas** [comment]
[Mageplaza Social Login](https://www.mageplaza.com/magento-2-social-login-extension/) is integrated with [One step checkout](https://www.mageplaza.com/magento-2-one-step-checkout-extension/)

You can learn see **Mageplaza One Step Checkout demo**

**Comment by afavata** [comment]
Thank you for your reply. ... One step checkout is not planned as next purchase.
We are more oriented towards to Mageplaza Affiliate Extension.
So is there a trick to make it shows on checkout page and/or sign in panel?
Thank you
Alex

**Comment by imsamthomas** [comment]
Hi @afavata ,

Mageplaza Social Login does not support default checkout, it only compatible with Mageplaza One Step Checkout we mentioned above.

**Comment by vinayak12** [comment]
hi,

I don't see social login in One step checkout user guild or demo ui.

**Comment by gixid192** [comment]
Hi @vinayak12 , there is no such setting :grinning: 
The reason is you can install and it just works out of the box, here you can see in our checkout pro page
![alt text](https://content.screencast.com/users/Lovemagic/folders/Jing/media/d1fd90a8-83ab-410f-9719-7e05e0b74ff8/2018-04-17_0924.png)
Demo link: http://oscpro.demo.mageplaza.com/
