### ISSUE TITLE
HTTP ERROR 500 RELOAD

### ISSUE THREAD

**Issue by dasy1234** [mageplaza/magento-2-social-login#71]
### Preconditions

1. Magento: 2.2

**Comment by Kenny1994** [comment]
Hi,
I'm Kenny from Mageplaza, regarding your reported problem, it caused by HybridAuth change the folder structure of Social APIs Library.
Please download and install Hybrid library to resolve the problem: https://github.com/mageplaza/magento-2-social-login/tree/library. 
On the other hand, please upgrade to the latest Social Login version to make sure it works fine.
If there are any further problems, please feel free to contact us.
Thank you!
